2014-07-21 14:39:09,650 ERROR ParTech.ImageLibrary.Core.Repositories.UserRepository -  - GetProfileByName - error [Sequence contains no elements] - 
    at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at System.Linq.Queryable.Single[TSource](IQueryable`1 source)
   at ParTech.ImageLibrary.Core.Repositories.UserRepository.GetUserProfileByName(String userName) in d:\Intern\ImageLibrary\ParTech.ImageLibrary.Core\Repositories\UserRepository.cs:line 315 


