2014-08-27 09:13:58,284 ERROR ParTech.ImageLibrary.Core.Repositories.UserRepository - david - SaveProfile - error [Sequence contains no elements] - 
    at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at System.Linq.Queryable.Single[TSource](IQueryable`1 source, Expression`1 predicate)
   at ParTech.ImageLibrary.Core.Repositories.UserRepository.SaveProfile(EditProfileModel profile) in d:\Intern\ImageLibrary\ParTech.ImageLibrary.Core\Repositories\UserRepository.cs:line 177 


2014-08-27 09:17:24,276 ERROR ParTech.ImageLibrary.Core.Repositories.UserRepository - david - SaveProfile - error [Sequence contains no elements] - 
    at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at System.Linq.Queryable.Single[TSource](IQueryable`1 source, Expression`1 predicate)
   at ParTech.ImageLibrary.Core.Repositories.UserRepository.SaveProfile(EditProfileModel profile) in d:\Intern\ImageLibrary\ParTech.ImageLibrary.Core\Repositories\UserRepository.cs:line 179 


2014-08-27 09:18:20,393 ERROR ParTech.ImageLibrary.Core.Repositories.UserRepository - david - SaveProfile - error [Sequence contains no elements] - 
    at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at System.Linq.Queryable.Single[TSource](IQueryable`1 source, Expression`1 predicate)
   at ParTech.ImageLibrary.Core.Repositories.UserRepository.SaveProfile(EditProfileModel profile) in d:\Intern\ImageLibrary\ParTech.ImageLibrary.Core\Repositories\UserRepository.cs:line 179 


2014-08-27 09:18:41,226 ERROR ParTech.ImageLibrary.Core.Repositories.UserRepository - david - SaveProfile - error [Sequence contains no elements] - 
    at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at System.Linq.Queryable.Single[TSource](IQueryable`1 source, Expression`1 predicate)
   at ParTech.ImageLibrary.Core.Repositories.UserRepository.SaveProfile(EditProfileModel profile) in d:\Intern\ImageLibrary\ParTech.ImageLibrary.Core\Repositories\UserRepository.cs:line 179 


2014-08-27 09:19:21,610 ERROR ParTech.ImageLibrary.Core.Repositories.UserRepository - david - SaveProfile - error [Sequence contains no elements] - 
    at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at System.Linq.Queryable.Single[TSource](IQueryable`1 source, Expression`1 predicate)
   at ParTech.ImageLibrary.Core.Repositories.UserRepository.SaveProfile(EditProfileModel profile) in d:\Intern\ImageLibrary\ParTech.ImageLibrary.Core\Repositories\UserRepository.cs:line 179 


