//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParTech.ImageLibrary.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public Invoice()
        {
            this.OrderLines = new HashSet<OrderLine>();
        }
    
        public int InvoiceID { get; set; }
        public int InvoiceNumber { get; set; }
        public System.DateTime Date { get; set; }
        public int UserID { get; set; }
        public int ProfileID { get; set; }
        public decimal InvoiceTotal { get; set; }
    
        public virtual ICollection<OrderLine> OrderLines { get; set; }
    }
}
