//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParTech.ImageLibrary.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoggedEvent
    {
        public int LoggedEventID { get; set; }
        public string Name { get; set; }
        public System.DateTime DateStarted { get; set; }
        public Nullable<System.DateTime> DateEnded { get; set; }
        public string Details { get; set; }
    }
}
