//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParTech.ImageLibrary.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderLine
    {
        public int OrderlineID { get; set; }
        public int ImageID { get; set; }
        public int BuyerID { get; set; }
        public int SellerID { get; set; }
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public System.DateTime created { get; set; }
        public System.DateTime updated { get; set; }
        public decimal Price { get; set; }
        public Nullable<int> InvoiceID { get; set; }
        public int UserID { get; set; }
    
        public virtual Image Image { get; set; }
        public virtual Invoice Invoice { get; set; }
        public virtual Product Product { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
