//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParTech.ImageLibrary.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Images = new HashSet<Image>();
            this.OrderLines = new HashSet<OrderLine>();
        }
    
        public int ProductID { get; set; }
        public string Name { get; set; }
        public string EDI { get; set; }
        public string SKU { get; set; }
        public int Year { get; set; }
        public string Material { get; set; }
        public string Size { get; set; }
        public System.DateTime created { get; set; }
        public System.DateTime updated { get; set; }
        public int UserID { get; set; }
        public int SeasonID { get; set; }
        public int GenderID { get; set; }
        public int CategoryID { get; set; }
        public Nullable<int> CollectionID { get; set; }
        public int BrandID { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual Category Category { get; set; }
        public virtual Collection Collection { get; set; }
        public virtual Gender Gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Image> Images { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderLine> OrderLines { get; set; }
        public virtual Season Season { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
