//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParTech.ImageLibrary.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public Profile()
        {
            this.UserProfiles = new HashSet<UserProfile>();
        }
    
        public int ProfileID { get; set; }
        public string CompanyName { get; set; }
        public int SalutationID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public string Address { get; set; }
        public string PostalCode { get; set; }
        public string City { get; set; }
        public int CountryID { get; set; }
        public System.DateTime created { get; set; }
        public System.DateTime updated { get; set; }
        public int LanguageID { get; set; }
    
        public virtual ICollection<UserProfile> UserProfiles { get; set; }
    }
}
