//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParTech.ImageLibrary.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCartItem
    {
        public int CartItemID { get; set; }
        public int UserID { get; set; }
        public int ImageID { get; set; }
        public System.DateTime created { get; set; }
    
        public virtual Image Image { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
