//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParTech.ImageLibrary.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubscriptionType
    {
        public SubscriptionType()
        {
            this.Profiles = new HashSet<Profile>();
        }
    
        public int SubscriptionTypeID { get; set; }
        public string Name { get; set; }
        public int Type { get; set; }
        public decimal Price { get; set; }
    
        public virtual ICollection<Profile> Profiles { get; set; }
    }
}
