//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParTech.ImageLibrary.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public UserProfile()
        {
            this.OrderLines = new HashSet<OrderLine>();
            this.Products = new HashSet<Product>();
            this.ShoppingCartItems = new HashSet<ShoppingCartItem>();
            this.webpages_Roles = new HashSet<webpages_Roles>();
        }
    
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public int AccountType { get; set; }
        public Nullable<int> ProfileID { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<OrderLine> OrderLines { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<ShoppingCartItem> ShoppingCartItems { get; set; }
        public virtual ICollection<webpages_Roles> webpages_Roles { get; set; }
    }
}
